#!/bin/bash

MYDIR=`dirname $0`
project_name=$1
auto=true

source $MYDIR/conf/$project_name.sh
source $MYDIR/modules/production_to_staging_setup.sh
source $MYDIR/modules/data_migration.sh
source $MYDIR/modules/user_generated_migration.sh
source $MYDIR/modules/set_permissions.sh
