#!/bin/bash
MYDIR=/home/lewis/wordpress-central/scripts
source $MYDIR/auto_stage
source $MYDIR/conf/$project_name.sh
source $MYDIR/modules/staging_to_production_setup.sh
source $MYDIR/modules/full_files_migration.sh
source $MYDIR/modules/set_permissions.sh
source $MYDIR/modules/data_migration.sh
source $MYDIR/modules/update_public_symlink.sh
