#!/bin/bash

MYDIR=`dirname $0`
echo "loading $MYDIR/modules/get_project_name.sh"
source $MYDIR/modules/get_project_name.sh
echo "loading $MYDIR/conf/$project_name.sh"
source $MYDIR/conf/$project_name.sh


echo "loading $MYDIR/modules/staging_to_production_setup.sh"
source $MYDIR/modules/staging_to_production_setup.sh

echo "loading $MYDIR/modules/data_migration.sh"
source $MYDIR/modules/data_migration.sh

echo "Done"